- name: install cron job (ansible-pull)
  cron:
    user: ansible
    name: "ansible provision"
    minute: "1"
    hour: "*/2"
    job: "/usr/bin/ansible-pull -o -U https://github.com/nialov/ansible-pull-nialov.git >> /home/ansible/ansible-pull.log"

- name: install cron job to auto update & upgrade on 15th of every month at 3.30
  cron:
    user: root
    name: "update and upgrade"
    day: "15"
    hour: "3"
    minute: "30"
    job: "apt update && apt upgrade -y >> /home/ansible/ansible-pull-update.log"

- name: install cron job to periodically remove ansible pull logs
  cron:
    user: root
    name: "remove ansible pull logs"
    job: "rm /home/ansible/ansible-pull.log /home/ansible/ansible-pull-update.log"
    day: "20"
    hour: "4"
    minute: "30"
    month: "*/3"

- name: remove dummy cron job (debugging)
  cron:
    user: ansible
    name: "dummy cron job"
    state: absent
