- name: install cron job (ansible-pull)
  cron:
    user: ansible
    name: "ansible provision"
    minute: "*/10"
    job: "/usr/bin/ansible-pull -o -U https://github.com/nialov/ansible-pull-nialov.git > /var/log/ansible-pull.log"

- name: install cron job to auto update & upgrade on 15th of every month at 3.30
  cron:
    user: root
    name: "update and upgrade"
    day: "15"
    hour: "3"
    minute: "30"
    job: "apt update && apt upgrade -y > /var/log/ansible-pull-update.log"
